#!/bin/zsh

vim `find ./ -iname '*.html' | grep -v vendor | grep -v eventmachine` `find ./ -iname '*.css' | grep -v eventmachine` `find ./ -iname '*.scss' | grep -v eventmachine` `find ./ -iname '*.js' | grep -v vendor | grep -v eventmachine`
